from google.adk.agents import LlmAgent, LoopAgent, SequentialAgent, ParallelAgent
from google.adk.agents.callback_context import CallbackContext
from google.adk.tools.tool_context import ToolContext
from google.adk.models.lite_llm import LiteLlm
from google.adk.tools.langchain_tool import LangchainTool
from google.genai import types
from agents.prompts import jury_prompt, jury_report_critic_prompt, jury_final_response_prompt

import logging
import os

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

deepseek_model  = LiteLlm(model="deepseek/deepseek-chat", api_key=os.getenv("DEEPSEEK_API_KEY"))
openai_model = LiteLlm(model="gpt-5-mini", api_key=os.getenv("OPENAI_API_KEY"),)

# lightrag_retrieve_tool = LangchainTool(lightrag_retrieve_sync)
# naiverag_retrieve_tool = LangchainTool(naiverag_retrieve_sync)

def exit_loop(tool_context: ToolContext):
    """Call this function ONLY when the critique indicates no further changes are needed, signaling the iterative process should end."""
    print(f"  [Tool Call] exit_loop triggered by {tool_context.agent_name}")
    tool_context.actions.escalate = True
    # Return empty dict as tools should typically return JSON-serializable output
    return {}

# ---------------- FACTORY: Jury+Critic Loop ----------------
def make_cross_loop(jury_name: str, critic_name: str, output_key: str, jury_model, critic_model):
    jury = LlmAgent(
        name=jury_name,
        description=f"{jury_name} compliance reviewer",
        instruction=jury_prompt.PROMPT,
        model=jury_model,
        tools=[
            exit_loop],
        output_key=output_key,
    )

    critic = LlmAgent(
        name=critic_name,
        description=f"{critic_name} reviewing {jury_name}'s report",
        instruction=jury_report_critic_prompt.PROMPT,
        model=critic_model,
    )

    return LoopAgent(
        name=f"{jury_name}Loop",
        description=f"{jury_name} (with {critic_name} cross-review)",
        sub_agents=[jury, critic],
        max_iterations=3,
    )

# ---------------- BUILD 4 JURORS ----------------
# DeepSeek jurors with OpenAI critics
loop_jury1 = make_cross_loop("JuryAgent1", "Critic1", "jury_report_1", deepseek_model, openai_model)
loop_jury2 = make_cross_loop("JuryAgent2", "Critic2", "jury_report_2", deepseek_model, openai_model)

# OpenAI jurors with DeepSeek critics
loop_jury3 = make_cross_loop("JuryAgent3", "Critic3", "jury_report_3", openai_model, deepseek_model)
loop_jury4 = make_cross_loop("JuryAgent4", "Critic4", "jury_report_4", openai_model, deepseek_model)

# ---------------- PARALLEL JURY ----------------
parallel_jury_agent = ParallelAgent(
    name="ParallelJuryAgent",
    description="Runs 4 jurors (DeepSeek + OpenAI) with cross-model critics in parallel",
    sub_agents=[loop_jury1, loop_jury2, loop_jury3, loop_jury4],
)

# ---------------- JUDGE (FINAL RESPONSE) ----------------
final_response_agent = LlmAgent(
    name="FinalResponseAgent",
    description="Judge merges jury outputs into one final compliance report",
    instruction=jury_final_response_prompt.PROMPT,
    model=deepseek_model,   
    output_key="final_report",
)

# ---------------- ROOT PIPELINE ----------------
jury_pipeline = SequentialAgent(
    name="JuryPipeline",
    description="Judge orchestrates → Parallel Jury Loops → Judge final report",
    sub_agents=[
        parallel_jury_agent,    # run jurors in parallel
        final_response_agent,   # judge merges into final report
    ],
)

root_agent = jury_pipeline

# jury_agent = LlmAgent(
#     name="JuryAgent",
#     description="Jury Agent tasked to create a report on the legal compliance assessment of provided feature",
#     instruction=jury_prompt.PROMPT,
#     model=litellm_model,
#     tools=[
#         naiverag_retrieve_tool,
#         # lightrag_retrieve_tool
#         exit_loop
#     ],
#     output_key="jury_report"
# )


# jury_report_critic_agent = LlmAgent(
#     name="JuryReportCriticAgent",
#     description=(
#         "Jury Report Critic Agent. This agent reviews the reports generated by the Jury Agent "
#         "and provides feedback or requests additional information as needed."
#     ),
#     instruction=jury_report_critic_prompt.PROMPT,
#     model=litellm_model
# )

# loop_report_agent = LoopAgent(
#     name="JuryReportAgent",
#     description=(
#         "Orchestrates the jury report generation and review process."
#     ),
#     sub_agents=[
#         jury_agent,
#         jury_report_critic_agent
#     ],
#     max_iterations=5,
# )

# final_response_agent = LlmAgent(
#     name="FinalResponseAgent",
#     description="Returns the final response to the judge",
#     instruction=jury_final_response_prompt.PROMPT,
#     model=litellm_model,
#     output_key="final_response",
#     # generate_content_config=types.GenerateContentConfig(temperature=0.5),
# )

# root_agent = SequentialAgent(
#     name="JuryRootAgent",
#     description=(
#         "Starts the research and report generation process and returns the final response"
#     ),
#     sub_agents=[
#         loop_report_agent,
#         final_response_agent
#     ],
# )