from google.adk.agents import LlmAgent, LoopAgent, SequentialAgent
from google.adk.agents.callback_context import CallbackContext
from google.adk.tools.tool_context import ToolContext
from google.adk.models.lite_llm import LiteLlm
from google.adk.tools.langchain_tool import LangchainTool
from google.genai import types
from agents.tools.lightrag_tools import lightrag_retrieve_sync
from agents.tools.naiverag_tools import naiverag_retrieve_sync
from agents.prompts import jury_prompt, jury_report_critic_prompt, jury_final_response_prompt

import logging
import os

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

litellm_model = LiteLlm(model="deepseek/deepseek-chat", api_key=os.getenv("DEEPSEEK_API_KEY"))

lightrag_retrieve_tool = LangchainTool(lightrag_retrieve_sync)
naiverag_retrieve_tool = LangchainTool(naiverag_retrieve_sync)

def exit_loop(tool_context: ToolContext):
    """Call this function ONLY when the critique indicates no further changes are needed, signaling the iterative process should end."""
    print(f"  [Tool Call] exit_loop triggered by {tool_context.agent_name}")
    tool_context.actions.escalate = True
    # Return empty dict as tools should typically return JSON-serializable output
    return {}

jury_agent = LlmAgent(
    name="JuryAgent",
    description="Jury Agent tasked to create a report on the legal compliance assessment of provided feature",
    instruction=jury_prompt.PROMPT,
    model=litellm_model,
    tools=[
        naiverag_retrieve_tool,
        # lightrag_retrieve_tool
        exit_loop
    ],
    output_key="jury_report"
)


jury_report_critic_agent = LlmAgent(
    name="JuryReportCriticAgent",
    description=(
        "Jury Report Critic Agent. This agent reviews the reports generated by the Jury Agent "
        "and provides feedback or requests additional information as needed."
    ),
    instruction=jury_report_critic_prompt.PROMPT,
    model=litellm_model
)

loop_report_agent = LoopAgent(
    name="JuryReportAgent",
    description=(
        "Orchestrates the jury report generation and review process."
    ),
    sub_agents=[
        jury_agent,
        jury_report_critic_agent
    ],
    max_iterations=5,
)

final_response_agent = LlmAgent(
    name="FinalResponseAgent",
    description="Returns the final response to the judge",
    instruction=jury_final_response_prompt.PROMPT,
    model=litellm_model,
    output_key="final_response",
    # generate_content_config=types.GenerateContentConfig(temperature=0.5),
)

root_agent = SequentialAgent(
    name="JuryRootAgent",
    description=(
        "Starts the research and report generation process and returns the final response"
    ),
    sub_agents=[
        loop_report_agent,
        final_response_agent
    ],
)